# Generated by Django 2.2 on 2019-04-04 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='', max_length=20)),
                ('mobilenumber', models.IntegerField(blank=True, default=8519002741)),
                ('player1', models.CharField(default='', max_length=10)),
                ('player2', models.CharField(blank=True, default='', max_length=10)),
                ('player3', models.CharField(blank=True, default='', max_length=10)),
                ('player4', models.CharField(blank=True, default='', max_length=10)),
                ('kills', models.IntegerField(default=0)),
                ('attendance', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('match_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('match_type', models.CharField(choices=[('SOLO', 'SOLO'), ('DUO', 'DUO'), ('SQUAD', 'SQUAD')], default='SOLO', max_length=10)),
                ('description', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('num_seats', models.IntegerField(null=True)),
                ('entry_fee', models.IntegerField(default=0)),
                ('prize', models.IntegerField(default=0)),
                ('per_kill', models.CharField(default=0, max_length=10)),
                ('room_details', models.CharField(default='Room id :--', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='results', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(default='SOLO', max_length=10)),
                ('slot_num', models.IntegerField(blank=True, default=1)),
                ('booktime', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
